const { Router } = require("express");
const listController = require("../controllers/listController");
const router = Router();
router.post("/createList", listController.createList);
router.post("/addToList/:listId/:problemId", listController.addToList);
router.post("/deleteList", listController.deleteList);
router.post("/deleteProblemFromList", listController.deleteProblemFromList);
router.post("/getList/:id", listController.getList);
router.post("/getListForHomePage/:id", listController.getListForHomePage);
module.exports = router;
